"""Added ProductItem table for many-to-many relationship

Revision ID: 5c722ec6a004
Revises: 034e2c18d960
Create Date: 2024-10-27 09:46:54.408228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c722ec6a004'
down_revision: Union[str, None] = '034e2c18d960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_code', table_name='products')
    op.drop_index('ix_products_id', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_table('products')
    op.drop_table('product_template_items')
    op.drop_index('ix_product_templates_code_prefix', table_name='product_templates')
    op.drop_index('ix_product_templates_description', table_name='product_templates')
    op.drop_index('ix_product_templates_id', table_name='product_templates')
    op.drop_index('ix_product_templates_name', table_name='product_templates')
    op.drop_table('product_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('code_prefix', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_templates_name', 'product_templates', ['name'], unique=False)
    op.create_index('ix_product_templates_id', 'product_templates', ['id'], unique=False)
    op.create_index('ix_product_templates_description', 'product_templates', ['description'], unique=False)
    op.create_index('ix_product_templates_code_prefix', 'product_templates', ['code_prefix'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_template_items',
    sa.Column('product_template_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_needed', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['product_template_id'], ['product_templates.id'], ),
    sa.PrimaryKeyConstraint('product_template_id', 'item_id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('product_template_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_template_id'], ['product_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_index('ix_products_code', 'products', ['code'], unique=1)
    # ### end Alembic commands ###
